version: '3'
services:
  database:
    container_name: practice-be-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    # Dockerfile이 있는 위치
    build: ./database
    # 내부에서 개방할 포트 : 외부에서 접근할 포트
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

